config:
 info: this is master branch , application-dev.yml ,version = 1

server:
  port: 8880

logging:
  level:
    com:
      example:
        ms:
          dao: debug
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 3000
    map-underscore-to-camel-case: true
  mapperLocations: classpath:mappers/*.xml
  type-aliases-package: com.d.ms.shopping.domain
spring:
  datasource:
    url: ENC(dYjXeetMIn9kn4LW4hR9IHI+jdUwHhRIOGljXqWrPPq046pLAzpXieJsTtlIhYGwAD+cNLuZtQhDtVsAcV3a2pV5XoPFuffEEkC1/U00OH4ON9YmjW0rQFEUg6xxjmNxr/HzNEwzpN8mmP+Wdc7CsKNrEpjYuFWb)
    username: ENC(DJ75WLEflKGNFC3kAkZMCQ==)
    password: ENC(RXUH3kgA0+4wrsOKRyc8vw==)
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    initialSize: 1
    maxActive: 2
    maxOpenPreparedStatements: 20
    maxWait: 60000
    minEvictableIdleTimeMillis: 300000
    minIdle: 1
    poolPreparedStatements: true
    testOnBorrow: false
    testOnReturn: false
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 60000
    type: com.alibaba.druid.pool.DruidDataSource
    validationQuery: select 'x'

# 验证密文时需要的密钥
jasypt:
  encryptor:
    password: lyh
